pipeline {
    agent any
    tools {
         maven "MAVEN3.9"
        jdk "JDK17"

    }
    
    environment {
        cluster = 'vroappprod'
        service = 'vproapptaskprod'
    }

    stages {
         stage('Deploy to prod ECS') {
            steps {
                withAWS(credentials: 'awscred', region: 'ap-south-1'){
                sh "aws ecs update-service  --cluster ${cluster} --service ${service} --force-new-deployment"
                }
            }
        }
}


